name: datastructures
version: 0.0.0
date: 31/12/2013
description: datastructures is a collection of standard data structures for the GAP programming language

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math.php

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math.php

GAP: "4.5.3"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://www-groups.mcs.st-andrews.ac.uk/~markusp/datastructures/
readme: http://www-groups.mcs.st-andrews.ac.uk/~markusp/datastructures/README
packageinfo: http://www-groups.mcs.st-andrews.ac.uk/~markusp/datastructures/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-andrews.ac.uk/~markusp/datastructures/datastructures-0.0.0.tar.gz

abstract: The <span class="pkgname">datastructures</span> package provides some    standard data structures.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
