name: datastructures
version: 0.1
date: 31/8/2017
description: |
    Collection of standard data structures for GAP

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math.php
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp
    - name: Max Horn
      url: http://www.quendi.de/math.php
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.8.7"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/datastructures
readme: README.md
packageinfo: https://gap-packages.github.io/datastructures/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/datastructures/releases/download/v0.1/datastructures-0.1.tar.gz

abstract: |
    The <span class="pkgname">datastructures</span> package provides some    standard data structures.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
